version: '3.4'

services:
    nginx:
        container_name: nginx
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - '80:80'
        volumes:
            - ./nginx/logs:/var/log/nginx
        restart: unless-stopped

    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '${MONGO_PORT}:27017'
        volumes:
            - data:/data/db
        env_file:
            - .env

    client:
        container_name: client
        build:
            dockerfile: Dockerfile
            context: ./client
        ports:
            - '${CLIENT_PORT}:3000'
        volumes:
            - ./client:/usr/app
            - /usr/app/node_modules
        env_file:
            - .env

    server:
        container_name: server
        build:
            dockerfile: Dockerfile
            context: ./server
        ports:
            - '${SERVER_PORT}:3000'
        volumes:
            - ./server:/usr/app
            - /usr/app/node_modules
        env_file:
            - .env
        depends_on:
            - mongo
            - redis

    redis:
        container_name: redis
        image: redis
        volumes:
            - data:/data/redis
        ports:
            - '6379:6379'
        restart: always

volumes:
    data:
        driver: local
